services:
  # ------------------ INFRASTRUCTURE ------------------
  postgres:
    image: postgres:16-alpine
    container_name: synapse_postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - synapse_net
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis/redis-stack-server:latest
    container_name: synapse_redis
    restart: unless-stopped
    networks:
      - synapse_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ------------------ BACKEND SERVICES ------------------
  api_gateway:
    container_name: synapse_api_gateway
    build:
      context: ./backend
      dockerfile: api_gateway/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    # Volumes for development: code changes on host are reflected in the container
    volumes:
      - ./backend/api_gateway:/app
      - ./backend/shared:/app/shared
    networks:
      - synapse_net
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  orchestrator_service:
    container_name: synapse_orchestrator
    build:
      # CORRECTED: Build context is now the parent 'backend' directory
      context: ./backend
      # CORRECTED: Path to Dockerfile is relative to the context
      dockerfile: orchestrator_service/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    # ADDED: Volumes for development to ensure consistency with other services
    volumes:
      - ./backend/orchestrator_service/app:/app
      - ./backend/shared:/app/shared
    networks:
      - synapse_net
    depends_on:
      redis:
        condition: service_healthy

  execution_workers:
    container_name: synapse_workers
    build:
      # CORRECTED: Build context is now the parent 'backend' directory
      context: ./backend
      # CORRECTED: Path to Dockerfile is relative to the context
      dockerfile: execution_workers/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    # ADDED: Volumes for development to ensure consistency with other services
    volumes:
      - ./backend/execution_workers/app:/app
      - ./backend/shared:/app/shared
    networks:
      - synapse_net
    depends_on:
      redis:
        condition: service_healthy

# ------------------ NETWORKS & VOLUMES ------------------
networks:
  synapse_net:
    driver: bridge

volumes:
  postgres_data:
    driver: local