name: Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.dev.txt
        python -m pip install -r backend/api_gateway/requirements.txt
        python -m pip install -r backend/orchestrator_service/requirements.txt
        python -m pip install -r backend/execution_workers/requirements.txt
    - name: Run tests
      run: pytest -q
